/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click(GDropList source, GEvent event) { //_CODE_:Components:574480:
  println("Components - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Components:574480:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:305656:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:305656:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:945949:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:945949:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Components = new GDropList(this, 270, 60, 90, 120, 5, 10);
  Components.setItems(loadStrings("list_574480"), 0);
  Components.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Components.addEventHandler(this, "dropList1_click");
  button1 = new GButton(this, 91, 317, 80, 30);
  button1.setText("RESET");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 276, 317, 80, 30);
  button2.setText("SAVE");
  button2.addEventHandler(this, "button2_click1");
}

// Variable declarations 
// autogenerated do not edit
GDropList Components; 
GButton button1; 
GButton button2; 
